"""Train the fixed four-stage recipe from random weights, evaluate, and render."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import shutil
import subprocess
import sys

import torch

from swapping.checkpointing import load_checkpoint
from swapping.pretrain import pretrain
from swapping.refine import parser as refinement_parser, refine
from swapping.reproducibility import runtime_manifest, sha256_file

ROOT = Path(__file__).resolve().parents[1]


def model_hash(state):
    """Hash tensor values, not checkpoint serialization or run-specific metadata."""
    digest = hashlib.sha256()
    for name, tensor in sorted(state.items()):
        array = tensor.detach().cpu().contiguous().numpy()
        digest.update(json.dumps([name, str(array.dtype), list(array.shape)]).encode())
        digest.update(array.tobytes())
    return digest.hexdigest()


def train_chain(output, smoke=False):
    if output.exists():
        raise FileExistsError(f"Choose a new output folder: {output}")
    recipe_path = ROOT/"configs/from_scratch_recipe.json"
    recipe = json.loads(recipe_path.read_text())
    output.mkdir(parents=True)
    manifest = runtime_manifest(ROOT, recipe, sys.argv)
    manifest.update(recipe=recipe, recipe_sha256=sha256_file(recipe_path), smoke=smoke,
                    external_checkpoint_inputs=[], stages=[], status="training")
    report = output/"reproduction.json"

    def record():
        report.write_text(json.dumps(manifest, indent=2, sort_keys=True)+"\n")

    record()
    parent = None
    for index, stage in enumerate(recipe["stages"]):
        if parent is not None and not parent.resolve().is_relative_to(output.resolve()):
            raise ValueError("Training may load only checkpoints generated by this run")
        directory = output/stage["name"]
        updates = 2 if smoke else stage["updates"]
        print(f"Stage {index+1}/4: {stage['name']}; seed={stage['seed']}; updates={updates}", flush=True)
        if stage["method"] == "pretrain":
            overrides = [f"run.output_dir={directory}", f"run.seed={stage['seed']}",
                         f"training.updates={updates}", f"optimizer.learning_rate={stage['learning_rate']}",
                         f"training.demonstration_source={stage['source']}"]
            if smoke:
                overrides += ["training.batch_size=2", "training.horizon=6", "training.validation_horizon=6",
                              "training.validation_count=1", "training.validation_interval=1"]
            checkpoint = pretrain(str(ROOT/recipe["config"]), overrides, str(parent) if parent else None)
        else:
            if parent is None:
                raise ValueError("Refinement requires this run's preceding stage")
            arguments = ["--variant", stage["variant"], "--parent", str(parent),
                         "--output-dir", str(directory), "--seed", str(stage["seed"]),
                         "--updates", str(updates), "--learning-rate", str(stage["learning_rate"])]
            if smoke:
                arguments += ["--batch-size", "2", "--horizon", "6", "--sampled-times", "4",
                              "--validation-horizon", "6", "--validation-count", "1",
                              "--structured-count", "1", "--validation-interval", "1"]
            checkpoint = refine(refinement_parser().parse_args(arguments))
        saved = load_checkpoint(checkpoint)
        expected_parent = str(parent) if parent else None
        if saved["parent_checkpoint"] != expected_parent:
            raise ValueError("Unexpected checkpoint ancestry")
        if parent is not None and saved["parent_sha256"] != sha256_file(parent):
            raise ValueError("Parent checkpoint hash mismatch")
        manifest["stages"].append({"name": stage["name"], "seed": stage["seed"], "updates": updates,
                                   "checkpoint": str(checkpoint), "parent": expected_parent,
                                   "checkpoint_sha256": sha256_file(checkpoint),
                                   "model_tensor_sha256": model_hash(saved["model"]),
                                   "selected_update": saved["global_update"]})
        record()
        parent = checkpoint
    shutil.copy2(parent, output/"selected.pt")
    manifest.update(status="training_complete", selected_checkpoint=str(output/"selected.pt"))
    record()
    return manifest


def verify_reference(manifest):
    """Compare freshly trained tensors and logs with the recorded reference hashes."""
    if manifest["smoke"]:
        raise ValueError("A smoke run cannot reproduce full-training reference weights")
    expected = json.loads((ROOT/"results/reproduction.json").read_text())
    references = {stage["name"]: stage for stage in expected["stages"]}
    comparisons = []
    for stage in manifest["stages"]:
        current = load_checkpoint(Path(stage["checkpoint"]))
        history_path = Path(stage["checkpoint"]).parent/"metrics.jsonl"
        history = [json.loads(line) for line in history_path.read_text().splitlines()]
        history_hash = hashlib.sha256(json.dumps(history, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
        reference = references[stage["name"]]
        comparisons.append({"stage": stage["name"],
                            "identical_model_tensors": model_hash(current["model"]) == reference["model_tensor_sha256"],
                            "identical_training_history": history_hash == reference["training_history_sha256"]})
    return {"all_model_tensors_identical": all(r["identical_model_tensors"] for r in comparisons),
            "all_training_histories_identical": all(r["identical_training_history"] for r in comparisons),
            "stages": comparisons}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=Path("runs/from_scratch"))
    parser.add_argument("--smoke", action="store_true", help="two updates per stage; no evaluation or GIFs")
    parser.add_argument("--verify-reference", action="store_true",
                        help="after training, compare tensor and log hashes with the reference results")
    args = parser.parse_args()
    if args.smoke and args.verify_reference:
        parser.error("--smoke and --verify-reference cannot be combined")
    if Path.cwd().resolve() != ROOT:
        parser.error(f"Run this command from {ROOT}")
    manifest = train_chain(args.output_dir, args.smoke)
    report = args.output_dir/"reproduction.json"
    if args.verify_reference:
        manifest["verification"] = verify_reference(manifest)
        report.write_text(json.dumps(manifest, indent=2, sort_keys=True)+"\n")
        if not all(manifest["verification"][key] for key in ("all_model_tensors_identical", "all_training_histories_identical")):
            raise RuntimeError(f"Training differs from the reference hashes; inspect {report}")
    if not args.smoke:
        for command in [
            ["scripts/evaluate.py", "--checkpoint", str(args.output_dir/"selected.pt"),
             "--output", str(args.output_dir/"validation.json")],
            ["scripts/generate_random_gallery.py", "--checkpoint", str(args.output_dir/"selected.pt"),
             "--output-dir", str(args.output_dir/"gifs")],
        ]:
            subprocess.run([sys.executable, *command], check=True)
    manifest["status"] = "smoke_complete" if args.smoke else "complete"
    report.write_text(json.dumps(manifest, indent=2, sort_keys=True)+"\n")
    print(json.dumps({"status": manifest["status"], "report": str(report)}, indent=2))


if __name__ == "__main__":
    main()
